### ISSUE TITLE
[enhancement] CNI should mark nodes according to existence of bridges

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/ovs-cni#37]
Daemon on each node will monitor available OVS bridges and set them on respective node label, by appending the bridge name to the label key name.
For example, if the following OVS bridges exists on the node:
```
br-red
br-yellow
br-blue
```
The the following node labels will be added:
```yaml
apiVersion: v1
kind: Node
metadata:
  labels:
    kubernetes.io/ovs-cni-br-red: 1
    kubernetes.io/ovs-cni-br-yellow: 1
    kubernetes.io/ovs-cni-br-blue: 1
```
~~~There will be a maximum number of supported bridges configured at the system. If more OVS bridges exists on the node that this number, an error messages should be logged, but the system should work with the bridges up to the allowed maximum.~~~

The bridges will be added/deleted periodically from the list.
> - "fake" bridges (ports) should be filtered out.
> - There might be OVS bridges which are not intended for our use, adding them to the list does no harm unless they are mapped to a requested network in the NetworkAttachmentDefinition CRD. This should be a configuration error in the NetworkAttachmentDefinition CRD, and not an issue that should be detected here. A future enhancement may be to add a list of blacklisted bridges as configuration.

A controller will run a MutatingAdmissionWebhook server that will receive the pod creation events, will look for pods that has the following annotation: ```k8s.v1.cni.cncf.io/networks```
If such annotation exists, the daemon will parse the list of network names, and will lookup each name into the list of network attachment CRDs of type ```ovs``` to get the bridge name from the network name. Based on these bridges, the following nodeAffinity sections (beta feature), will be added to the pod.

For example, assuming that:  ```k8s.v1.cni.cncf.io/networks=red-net,blue-net```
And that the following CRDs are configured:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: red-net
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "br-red",
    }'
```
and:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: blue-net
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "br-blue",
    }'
```
The mutating web hook will add the following nodeAffinity:
```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubevirt.io/ovs-cni-br-red
            operator: Exist
          - key: kubevirt.io/ovs-cni-br-blue
            operator: Exists
```

As mentioned above, two processes should exist:
- distributed daemon that is doing the bridge discovery on the nodes
- centralized controller doing the admission as well as the translation between the network name and the bridge name (using the NetworkAttachmentDefinition CRD)
